---
version: '3'

env:
  env_file: "dev.env"

tasks:
  default:
    cmds:
      - echo "****** Task Manager ********"
      - echo "Task file for working on task-manager app"
  setup:
    cmds:
      - source {{.env_file}} && export TAG REPO && envsubst < values-template.yaml > values-$ENV.yaml
  deploy:
    cmds:
      - source {{.env_file}} && helm upgrade $COMPONENT . --install --values values-$ENV.yaml --create-namespace --namespace $NAMESPACE --dry-run
    deps:
      - setup