{{ if .Values.config.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-manager.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.configMap | nindent 2 }}
{{- end }}
