{{ if .Values.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
data: {{ range .Files.Lines .Values.config.secrets.fileName }}
  {{ . }}{{ end }}
{{- end }}